### ISSUE TITLE
[BUG] Bots showing in ;top

### ISSUE THREAD

**Issue by sujaykonda** [gubareve/trivia-bot#15]
**Describe the bug**
One very new servers, if you do ;top, sometimes a bot will appear on the leaderboard

**To Reproduce**
1. Create a new server with just yourself in it
2. Invite a random bot
3. Invite trivia bot
4. do ;top and you will see the bot on the leaderboard. 

**Expected behavior**
I thought only humans can appear on the leaderboard because if you use prefix say ;trivia it wont work. 

**Screenshots**
![image](https://user-images.githubusercontent.com/50930165/84073836-8c7b3380-a99f-11ea-84e7-ee7c6cd56286.png)

idk if this will work

**Info (please complete the following information):**
 - Server: Debates + Chat
 - Device: Laptop

**Additional context**
None

**Comment by WickedTree** [comment]
Ok! Thanks for your feedback! I will fix this later today!

**Comment by gubareve** [comment]
Yeah im going to make leaderboard bot only soon. Thanks for the review.

**Comment by gubareve** [comment]
I will also change null to 0.

**Comment by gubareve** [comment]
Fixed in #16
