### ISSUE TITLE
Loophole

### ISSUE THREAD

**Issue by hvhvuu** [gubareve/trivia-bot#18]
**Describe the bug**
There is a loophole to your bot. When the timer expires to a question you do not lose points. This can mean the user could expire the question if they do not know and answer the questions that they know hence not losing any points at all.

**To Reproduce**
1. ;trivia
2. time runs out

**Expected behavior**
It should deduct points from the user because their time ran out. But it doesn't.

**Screenshots**

**Info (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by gubareve** [comment]
Im starting to work on this.

**Comment by gubareve** [comment]
Resolved in 5760a9c
