### ISSUE TITLE
[BUG] there bug in my monitor

### ISSUE THREAD

**Issue by Romvnly-Gaming** [gubareve/trivia-bot#65]
**Describe the bug**

**To Reproduce**
4. Something wrong happens

**Expected behavior**

**Screenshots**

**Info (please complete the following information):**
 - Server: [e.g. DM's, Help Server]
 - Device: [e.g. Phone]
 - Screenshot of ;version:

**Additional context**

**Comment by gubareve** [comment]
no

**Comment by Romvnly-Gaming** [comment]
did you fix the bug?
